const types = {
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  FAIL_LOGIN: 'FAIL_LOGIN',
  LOGOUT: 'LOGOUT',
  LOGGED_OUT: 'LOGGED_OUT',
  CHECK_AUTHENTICATION: 'CHECK_AUTHENTICATION',
  GET_PRODUCTS: 'GET_PRODUCTS',
  SUCCESS_GET_PRODUCTS: 'SUCCESS_GET_PRODUCTS',
  FAIL_GET_PRODUCTS: 'FAIL_GET_PRODUCTS',
  GET_USER_INFO: 'GET_USER_INFO',
  SUCCESS_GET_USER_INFO:'SUCCESS_GET_USER_INFO',
  FAIL_GET_USER_INFO:'FAIL_GET_USER_INFO',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  SUCCESS_UPDATE_USER_INFO:'SUCCESS_UPDATE_USER_INFO',
  FAIL_UPDATE_USER_INFO:'FAIL_UPDATE_USER_INFO',
}

export default types
